on:
  issue_comment:
    types: [created]
name: Invite a new collaborator

jobs:
  build:
    name: Invite contributor to the Org
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@master
    - name: invite-contributor
      uses: jmertic/invite-based-on-comment@patch-1
      if: contains(github.event.issue.labels.*.name, 'collaborator add')
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SECRET_IBC }}
        TEAM_ID: 4418097
        ORG: 'genevaers'
        SELF_INVITE: false 
